services:
  broker:
    build:
      context: ./broker
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: always
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./client:/app
